### ISSUE TITLE
TypeError: this.getPane(...) is undefined

### ISSUE THREAD

**Issue by ultimate-tester** [Leaflet/Leaflet.TileLayer.NoGap#4]
When trying to use this library, I get the following:

`TypeError: this.getPane(...) is undefined`

Even the example provided in this repo suffers from this.
I tried every version of jsleaflet from 1.4.0 to 1.1.0. None of them work.
Is this library useable?

**Comment by ultimate-tester** [comment]
So I guess this means that the library is not used anymore? Why close it without comment?

**Comment by IvanSanchez** [comment]
> Why close it without comment?

Because your "Is this library useable?" wording felt so rude that I had a brainfart and didn't know how to reply to that.

Don't fret, everything works as of 3bb3b97a72658780ce04d4b240d432e056857015.

Nevertheless I feel obliged to link to ["How To Ask Questions The Smart Way"](http://www.catb.org/esr/faqs/smart-questions.html) and ["How to report bugs effectively"](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by ultimate-tester** [comment]
Don't worry, I never meant it as a rude comment. I was actually asking a serious question which is not weird on a repo that had it's last update 2 years ago (now 19 hours ago).

Thanks for your action and feedback. I'm sure to read those two pages you linked to.

**Comment by IvanSanchez** [comment]
Tip: Something like "I see this project hasn't seen maintained for a while" sounds much better than "Does this even work?"

**Comment by ghost** [comment]
@ultimate-tester If the `this.getPane(...)` is undefined, you may need to use `this.createPane(...)` first. Just something I ran into recently while working on a project. I realize this issue is old and closed, but worth a mention. Cheers!
